name: esi0hub
services:
  - name: web
    environment_slug: static-sites
    github:
      repo: esihub/esi-hub
      branch: main
    routes:
      - path: /
        preserve_path: true
        destination_dir: /
      - path: /docs
        preserve_path: true
        destination_dir: /doc-esi
      - path: /logo
        preserve_path: true
        destination_dir: /logo-esi
    static_sites:
      - build_command: ""
        output_dir: "/"
